apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  type: LoadBalancer
  ports:
    - port: 21
      protocol: TCP
  selector:
    app: ftps-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-lbl
  template:
    metadata:
      labels:
        app: ftps-lbl
    spec:
      containers:
        - image: ftps_img
          imagePullPolicy: Never
          name: ftps
          ports:
            - containerPort: 21
